### ISSUE TITLE
URGENT: Issue with 1.1.7 formula

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#15]
@CAMOBAP795 can you please help with this? Thanks!

Trace:

```sh
lmka-mm8a01dty3:test ts$ brew tap
adoptopenjdk/openjdk
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
riboseinc/metanorma
lmka-mm8a01dty3:test ts$ brew upgrade metanorma
Updating Homebrew...
Error: riboseinc/metanorma/metanorma 1.1.7 already installed
lmka-mm8a01dty3:test ts$ metanorma new -t csd
Traceback (most recent call last):
       17: from /Users/ts/.gem/ruby/2.5.3/bin/metanorma:23:in `<main>'
       16: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
       15: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:309:in `synchronize'
       14: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:311:in `block in activate_bin_path'
       13: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:243:in `finish_resolve'
       12: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:408:in `resolve_current'
       11: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:396:in `resolve'
       10: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:188:in `resolve'
       9: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
       8: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:78:in `resolve'
       7: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:137:in `process_topmost_state'
       6: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `attempt_to_activate'
       5: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:330:in `attempt_to_activate_existing_spec'
       4: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:469:in `push_state_for_requirements'
       3: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:9:in `search_for'
       2: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
       1: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `block in search_for'
/Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: 'metanorma-mpfd (~> 0.1.0)' requires 'metanorma-standoc (~> 1.1.0)' (Gem::UnsatisfiableDependencyError)
lmka-mm8a01dty3:test ts$ 
```

This line indicates there is a dependency error:
```
/Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: 'metanorma-mpfd (~> 0.1.0)' requires 'metanorma-standoc (~> 1.1.0)' (Gem::UnsatisfiableDependencyError)
```

**Comment by CAMOBAP795** [comment]
Ok

**Comment by opoudjis** [comment]
I've been asked to remove the dependency in https://github.com/metanorma/metanorma-cli/issues/70, but that is not addressing the issue.

metanorma-standoc is up to 1.1.8. I have refreshed Gemfile.lock on my machine, and the dependency of metanorma-cli on metanorma-mpfd has not hitherto been an issue; nor has it on Travis. So something else is going on. And I am not convinced that removing mpfd and rsd is going to fix it.

**Comment by opoudjis** [comment]
I am pushing a version of metanorma-cli without the MPFD and RSD gems in the gemspec. And since I am convinced this is not going to fix the issue, this issue must remain open. I will certainly not push an updated metanorma-cli gem until this has been further investigated.

**Comment by CAMOBAP795** [comment]
@ronaldtse I cannot have a look right now, maybe you have a chance to check/confirm that issue exists after formula reinstall?

I mean check:
```
brew uninstall metanorma
brew install metanorma
```

**Comment by ronaldtse** [comment]
My point was that those gems should be removed from default anyway, it is possible that there is another issue here in play.

**Comment by ronaldtse** [comment]
@camobap795 I think you can add a test to the Homebrew formula to test install, uninstall (then it shouldn’t work), then install again (to see if it works again).

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please clarify how you add `riboseinc/metanorma` from `brew tap` output?

**Comment by ronaldtse** [comment]
The formula was previously https://github.com/riboseinc/homebrew-metanorma , now it is https://github.com/metanorma/homebrew-metanorma . So this is an old tap.

**Comment by ronaldtse** [comment]
@CAMOBAP795 you should add this to the formula test to ensure it works:

```
brew uninstall metanorma
brew install metanorma
```

**Comment by CAMOBAP795** [comment]
@ronaldtse It works locally, I think no reason to check it because if it doesn' work it will point to brew issue

I think it makes more sense to test upgrade from 1.1.6 to 1.1.7 for instance

On it

**Comment by CAMOBAP795** [comment]
I have added uninstall/install test and upgrade tests both works good

@ronaldtse regarding issue above looks like something wrong happens during installation (I have no idea what exactly)

Could you please run `brew uninstall metanorma && brew install metanorma` and confirm that issue still exists?

**Comment by ronaldtse** [comment]
Verified fixed using the above command. Closing this issue.
