### ISSUE TITLE
Ruby 2.4.0 must be installed

### ISSUE THREAD

**Issue by opoudjis** [metanorma/homebrew-metanorma#21]
Just installed homebrew-metanorma on a High Sierra (10.13.4) machine:

````
==> gem install metanorma-cli-1.1.8.gem
Last 15 lines from /Users/nnicholas/Library/Logs/Homebrew/metanorma/03.gem:
install
metanorma-cli-1.1.8.gem

ERROR:  Error installing metanorma-cli-1.1.8.gem:
	html2doc requires Ruby version >= 2.4.0.
````

The move to eliminate Ruby 2.3.x support is recent (https://github.com/metanorma/metanorma/issues/56)

**Comment by CAMOBAP795** [comment]
Thanks, @opoudjis this block:
 - https://github.com/metanorma/homebrew-metanorma/pull/20
 - https://github.com/metanorma/homebrew-metanorma/pull/19

**Comment by CAMOBAP795** [comment]
Done
