### ISSUE TITLE
Instructions: “brew tap riboseinc/metanorma”?

### ISSUE THREAD

**Issue by strogonoff** [metanorma/homebrew-metanorma#22]
Instructions at https://www.metanorma.com/blog/01-23-2019/metanorma-on-macos-via-homebrew/ tell the user to `brew tap riboseinc/metanorma`, however on GitHub it’s now under metanorma/metanorma. Could it be that those instructions are outdated?

**Comment by ronaldtse** [comment]
Sorry you’re right — it’s outdated. Can you help fix it? :smile:

**Comment by strogonoff** [comment]
Done, new instructions:

```
brew tap metanorma/metanorma
brew install metanorma
```
