### ISSUE TITLE
Write script to automatically bump metanorma-cli version and dependencies

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#32]
As title.

**Comment by CAMOBAP795** [comment]
@ronaldtse should this one be reported to https://github.com/metanorma/cimas

**Comment by ronaldtse** [comment]
@CAMOBAP795 how about this?
https://github.com/mislav/bump-homebrew-formula-action

**Comment by CAMOBAP795** [comment]
Done
