### ISSUE TITLE
(URGENT) Fix brew install on macOS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#34]

**Comment by CAMOBAP795** [comment]
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#push

**Comment by wsdwl** [comment]
Same still here:
lmka-mm8a01dty3:~ ts$ brew upgrade
==> Upgrading 1 outdated package:
metanorma/metanorma/metanorma 1.1.8 -> 1.2.9
==> Upgrading metanorma/metanorma/metanorma 
==> Downloading https://github.com/metanorma/metanorma-cli/archive/v1.2.9.tar.gz
Already downloaded: /Users/ts/Library/Caches/Homebrew/downloads/4905a092b73a087016cd903eebe91c803e3c29217b8e71b182ec37fc7a39af78--metanorma-cli-1.2.9.tar.gz
==> gem build metanorma-cli.gemspec
==> gem install metanorma-cli-1.2.9.gem
Last 15 lines from /Users/ts/Library/Logs/Homebrew/metanorma/02.gem:
2020-02-24 18:27:18 +0100

gem
install
metanorma-cli-1.2.9.gem

ERROR:  Error installing metanorma-cli-1.2.9.gem:
	metanorma requires Ruby version >= 2.4.0.
Successfully installed rchardet-1.8.0
Successfully installed git-1.6.0
Successfully installed asciidoctor-2.0.10

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/metanorma/homebrew-metanorma/issues

These open issues may also help:
Write script to automatically bump metanorma-cli version and dependencies https://github.com/metanorma/homebrew-metanorma/issues/32

==> Checking for dependents of upgraded formulae...
==> No dependents found!
lmka-mm8a01dty3:~ ts$ brew upgrade ruby
Warning: ruby 2.7.0 already installed

**Comment by ronaldtse** [comment]
@wsdwl are you using macOS 10.5? 10.5 comes with Ruby 2.6+. If you're on macOS 10.4 you will need to install rbenv to upgrade ruby.

Using homebrew to upgrade Ruby can be dangerous as it comes with macOS.

**Comment by wsdwl** [comment]
10.14.6

**Comment by ronaldtse** [comment]
@wsdwl this is a good explanation on how to install Ruby 2.6+ on macOS:

https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-macos

Just follow steps 1-3, and it should work. 😉

**Comment by CAMOBAP795** [comment]
The task is related to publishing 'brew install metanorma'

**Comment by ronaldtse** [comment]
Closed, already done.
