### ISSUE TITLE
Integrate PDF setup into build script

### ISSUE THREAD

**Issue by opoudjis** [metanorma/homebrew-metanorma#36]
Integrate instructions from https://github.com/metanorma/mn-native-pdf/blob/master/README.adoc, as we are now integrating the functionality of that repository into metanorma

**Comment by CAMOBAP795** [comment]
Well... `homebrew` doesn't allow arbitrary script execution, so AFAIK we have 2 options:
1. rewrite https://github.com/fontist/vista-fonts-installer/blob/master/vista-fonts-installer.sh with ruby and embed it in the formula
2. add [`caveats`](https://www.rubydoc.info/github/Homebrew/brew/Formula:caveats) (a message which is shown after formula installation) to ask the user to execute it on his own

To me, option N2 looks more appropriate

@opoudjis @ronaldtse if you have other ideas about this please let me know

**Comment by ronaldtse** [comment]
> 1. rewrite https://github.com/fontist/vista-fonts-installer/blob/master/vista-fonts-installer.sh with ruby and embed it in the formula

Actually @abunashir has already been working on this which should be done this week: https://github.com/fontist/fontist/issues/5

So we should just move on to use 2, where we add a `caveats` message to ask user to run `metanorma setup` afterwards?

**Comment by CAMOBAP** [comment]
Done
