### ISSUE TITLE
Suggest adoc for ietf/xml2rfc testing

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/homebrew-metanorma#37]
For now, we have only test cases for:
 - iso
 - csd
 - standoc

It will be nice to add adoc for ietf/xml2rfc testing

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse maybe you have some suggestions for this?

**Comment by ronaldtse** [comment]
rfc-asciidoc-rfc?

**Comment by CAMOBAP795** [comment]
@ronaldtse  if possible some really minimal example, if you can point me to the line in `adoc` which 'triggers' xml2rfc invocation it will be enough for me

**Comment by opoudjis** [comment]
> @ronaldtse if possible some really minimal example, if you can point me to the line in adoc which 'triggers' xml2rfc invocation it will be enough for me

I do not understand what you mean. xml2rfc is required to convert RFC XML into HTML and TXT; it is triggered by metanorma.

I'm making up a minimal example for you.

**Comment by opoudjis** [comment]
[a.adoc.zip](https://github.com/metanorma/homebrew-metanorma/files/4437503/a.adoc.zip)

**Comment by CAMOBAP795** [comment]
Thanks, I hope the reduced version of it:

```
:doctype: rfc
:mn-document-class: ietf 
:mn-output-extensions: xml,rfc,txt,html,nits,rxl
:docfile: document.adoc

== Clause
Clause
```

will works also

**Comment by CAMOBAP795** [comment]
Fixed
