### ISSUE TITLE
`brew install` problem with openjdk

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#43]
A user reports the following error message after running `brew install metanorma`:

```
openjdk-13.0.1.jdk cannot be opened because the developer cannot be
verified.
https://github.com/jenv/jenv/issues/272
```

How can he fix this? 

Ping @CAMOBAP795 . Thanks!

**Comment by ronaldtse** [comment]
I believe this issue is caused by Catalina requiring macOS notarization of all binaries, and seems that the OpenJDK 13 package is not notarized.

Relevant issue:
https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/267


Possible workaround 1:
`brew cask install adoptopenjdk --no-quarantine`

Possible workaround 2:

1. Run `/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/bin/java` in the Terminal app to trigger the OpenJDK 13 binary

2. Open MacOS "System Preferences”
3. Click on "Security & Privacy”
4. Go to "General” tab
5. Click “Allow" at the bottom

**Comment by CAMOBAP795** [comment]
We have a transitive dependency on `openjdk` via `plantuml`

Unfortunately, we cannot do much about this, except adding extra caveats

@ronaldtse how do you think about this?

**Comment by ronaldtse** [comment]
@CAMOBAP795 can we use the system's JAVA version so the user doesn't need to install extra OpenJDK? e.g. https://apple.stackexchange.com/questions/273844/homebrew-why-is-java-not-installed-as-a-dependency-for-tomcat

**Comment by CAMOBAP795** [comment]
@ronaldtse I think we can, to be honest IDK why plantuml have openjdk dependency

I will try to move our formula to internal plantuml

**Comment by ronaldtse** [comment]
@CAMOBAP Metanorma relies on mn2pdf (which is in Java) and also PlantUML (also in Java), so we depend on Java. It is fine to rely on openjdk, and we should also have one "depends_on "openjdk""

**Comment by CAMOBAP** [comment]
@ronaldtse I tried to install plantuml on our own to use system java, but I forgot that starting from OSX 10.7 java isn't preinstalled https://stackoverflow.com/questions/13898870/is-java-runtime-pre-installed-on-mac-osx

PR is ready for review https://github.com/metanorma/homebrew-metanorma/pull/45

**Comment by CAMOBAP** [comment]
Merged
