### ISSUE TITLE
Add formula to install packed-mn version for easier setup

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#53]
Maybe a separate formula while we're still testing?

Since packed-mn is platform + architecture specific.

**Comment by ronaldtse** [comment]
Lins with https://github.com/metanorma/packed-mn/pull/47

**Comment by ronaldtse** [comment]
@CAMOBAP please check the Homebrew formula for Terraform, they are single binary with architecture specific, too.

**Comment by CAMOBAP** [comment]
Closed as duplicate of https://github.com/metanorma/homebrew-metanorma/issues/57
