### ISSUE TITLE
Python issue with installing when previous brew metanorma version installed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#54]
Issue with installing when previous brew metanorma version installed.

Reported by @douglm.

```
Error: Cannot link python
Another version is already linked: /usr/local/Cellar/python/3.7.4_1
```

**Comment by CAMOBAP** [comment]
@douglm could you please share more details:
 - is this issue still actual for you?
 - maybe you remember which version was installed before?

**Comment by CAMOBAP** [comment]
Also, this issue can be resolved by upgrading python to the latest one python@3.9, @douglm feel free to reopen if this issue still affects you
