### ISSUE TITLE
(URGENT) homebrew-metanorma version not tagged according to metanorma-cli

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#59]
metanorma-cli is now at 1.3.7.3!

<img width="718" alt="Screen Shot 2020-09-12 at 9 45 22 AM" src="https://user-images.githubusercontent.com/11865/92984439-ae271200-f4dc-11ea-809f-0daca3ff1ced.png">

**Comment by CAMOBAP** [comment]
@ronaldtse it is, https://github.com/metanorma/homebrew-metanorma/actions/runs/250748731

Maybe there are some delay, but according to CI history everything in place

It failed because of an update in brew by itself but this will be fixed by https://github.com/metanorma/homebrew-metanorma/pull/58
