### ISSUE TITLE
Install latest java

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/homebrew-metanorma#62]
Metanorma installer should install Java version 8u241 and above. Even when previous java was pre-installed before in system.

Initially the problem occured on MacOS with installed java version "1.8.0_60".
java -version
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Resulted PDF doesn't have a math equations. 

The reason - some flavors uses OTF fonts, but only Java 8u241 and above supports it. 
(https://github.com/metanorma/mn2pdf/issues/51). 

Also this issue relates to linux setup also.

Windows installer installs OpenJDK version 14 and there isn't issue there.

**Comment by CAMOBAP** [comment]
Waiting for response https://github.com/Homebrew/homebrew-cask/issues/16383#issuecomment-810258211

**Comment by ronaldtse** [comment]
@CAMOBAP can you use this?
https://github.com/Homebrew/homebrew-cask/blob/e697ce1dd5f3131d251c2a2ab4579cd628158315/Casks/adoptopenjdk.rb

**Comment by CAMOBAP** [comment]
@ronaldtse isn't clear how adoptopenkjdk different from openjdk formula. I think we need make sure that we set JAVA_HOME before metanorma call like this https://github.com/Homebrew/homebrew-core/commit/e36e5eee1f3e4230b07871a1920fda77d66737cc#diff-6014ed06ab5d0e0a2810549f7fae7744c7775cce3dae998f5bc13a29f279c7d6R32

BTW @Intelligent2013 Did you observed this issue on MacOS on CI or somewhere else?

**Comment by Intelligent2013** [comment]
> BTW @Intelligent2013 Did you observed this issue on MacOS on CI or somewhere else?
Actually initial problem was on MacOS by @opoudjis. I just  I don't have MacOS.

**Comment by CAMOBAP** [comment]
Done https://github.com/metanorma/homebrew-metanorma/pull/69
