### ISSUE TITLE
Move xml2rfc to an independent formula

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#79]
Most of these dependencies are for xml2rfc and idnits. Let's move them to a separate dependency.

https://github.com/metanorma/homebrew-metanorma/blob/a0c39fab59b573f9d83c2ae7fc03a31864b9f246/Formula/metanorma.rb#L161

**Comment by CAMOBAP** [comment]
Totally agree, moreover brew has `xml2rfc` formula before, but it looks like it's removed already

**Comment by CAMOBAP** [comment]
Done
